# Generated by Django 2.2.2 on 2019-07-10 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatelineForHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateField(verbose_name='Дата заселения')),
                ('time_to', models.DateField(verbose_name='Дата выселения')),
            ],
            options={
                'verbose_name_plural': 'Временная ось для пребывания в отелях',
                'get_latest_by': 'time_from',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название события')),
                ('manager', models.CharField(blank=True, max_length=200, verbose_name='Менеджер группы туристов')),
                ('manager_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('p', 'планируется'), ('c', 'длится'), ('e', 'закончилось')], default='p', help_text='Статус события', max_length=1)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название экскурсии', max_length=300)),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('date_of_arrival', models.DateField(blank=True, null=True, verbose_name='Дата прибытия группы')),
                ('date_of_departure', models.DateField(blank=True, null=True, verbose_name='Дата убытия группы')),
                ('status', models.CharField(blank=True, choices=[('f', 'группа формируется'), ('c', 'группа прибыла'), ('g', 'группа уехала')], default='r', max_length=1, verbose_name='Статус группы')),
            ],
            options={
                'verbose_name_plural': 'Группы',
                'ordering': ['date_of_arrival'],
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название питания', max_length=300)),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Питание',
                'verbose_name_plural': 'Питание',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО Туриста')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='email')),
                ('note', models.TextField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('visa', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия визы')),
                ('insurance', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия страховки')),
                ('passport', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия паспорта')),
                ('others', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Другие документы')),
                ('status', models.CharField(blank=True, choices=[('w', 'ожидается приезд'), ('n', 'ничем не занят'), ('e', 'на экскурсии'), ('p', 'питается'), ('y', 'уехал'), ('g', 'не в группе')], default='w', max_length=1, verbose_name='Статус туриста')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Туристы',
                'permissions': (('can_edit', 'Editing data'), ('can_get_report', 'Getting report')),
            },
        ),
        migrations.CreateModel(
            name='TimelineForNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField(verbose_name='Начало')),
                ('time_to', models.DateTimeField(verbose_name='Окончание')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Event', verbose_name='Событие')),
                ('nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Nutrition', verbose_name='Питание')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist', verbose_name='Турист')),
            ],
            options={
                'verbose_name_plural': 'Время для питания',
                'get_latest_by': 'date_from',
            },
        ),
        migrations.CreateModel(
            name='TimelineForExcursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField(verbose_name='начало экскурсии')),
                ('time_to', models.DateTimeField(verbose_name='окончание экскурсии')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Event', verbose_name='Событие')),
                ('excursion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Excursion', verbose_name='Экскурсии')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist', verbose_name='Турист')),
            ],
            options={
                'verbose_name_plural': 'Время для экскурсий',
                'get_latest_by': 'date_from',
            },
        ),
        migrations.AddField(
            model_name='nutrition',
            name='timelines',
            field=models.ManyToManyField(through='tourists.TimelineForNutrition', to='tourists.Tourist'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название отеля', max_length=300, verbose_name='Название отеля')),
                ('addres', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('cost_for_one_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('datelines', models.ManyToManyField(through='tourists.DatelineForHotel', to='tourists.Tourist')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.AddField(
            model_name='excursion',
            name='timelines',
            field=models.ManyToManyField(through='tourists.TimelineForExcursion', to='tourists.Tourist'),
        ),
        migrations.AddField(
            model_name='datelineforhotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Hotel'),
        ),
        migrations.AddField(
            model_name='datelineforhotel',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist'),
        ),
    ]
